# Generated by Django 3.2.17 on 2023-03-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('enrollment', models.CharField(max_length=200)),
                ('if_full', models.BooleanField(default=False)),
            ],
        ),
    ]
