# Generated by Django 4.1.6 on 2023-04-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
