# Generated by Django 3.2.17 on 2023-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferClass', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('transferCredits', models.CharField(max_length=200)),
                ('UVAClass', models.CharField(max_length=200)),
                ('UVACredits', models.CharField(max_length=200)),
            ],
        ),
    ]
