# Generated by Django 4.1.6 on 2023-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='school_name',
            field=models.CharField(default='uva', max_length=200),
        ),
    ]
