# Generated by Django 4.1.6 on 2023-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_approvedtransfer_as_message_as_newapprovedschool_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedtransfer',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
