# Generated by Django 4.1.6 on 2023-03-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_message_equivalency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(default='uva', max_length=200)),
                ('equivalency_name', models.CharField(default='None', max_length=200)),
            ],
        ),
    ]
