# Generated by Django 3.2.17 on 2023-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20230424_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_as',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
