# Generated by Django 4.1.6 on 2023-04-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_transfer'),
        ('login', '0005_approvedtransfer'),
    ]

    operations = [
    ]
