# Generated by Django 3.2.17 on 2023-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_0003_transfer_0005_approvedtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApprovedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='UVA_credits',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='class_credits',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='class_number',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(default='Class', max_length=200),
        ),
    ]
