# Generated by Django 3.2.17 on 2023-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20230403_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTransfer_AS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(default='uva', max_length=200)),
                ('equivalency_name', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message_AS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(default=0, max_length=200)),
                ('message_text', models.CharField(default='Class', max_length=200)),
                ('class_credits', models.CharField(default=0, max_length=200)),
                ('school_name', models.CharField(default='uva', max_length=200)),
                ('equivalency_name', models.CharField(default='None', max_length=200)),
                ('UVA_credits', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewApprovedSchool_AS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_AS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferClass', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('transferCredits', models.CharField(max_length=200)),
                ('UVAClass', models.CharField(max_length=200)),
                ('UVACredits', models.CharField(max_length=200)),
            ],
        ),
    ]
