# Generated by Django 3.2.18 on 2023-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_approvedtransfer_as_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedtransfer_as',
            name='reason',
        ),
        migrations.AddField(
            model_name='deniedtransfer_as',
            name='reason',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
