# Generated by Django 3.2.18 on 2023-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_approvedtransfer_as_message_as_newapprovedschool_as_transfer_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='site_url',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
