# Generated by Django 3.2.18 on 2023-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_message_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_as',
            name='site_url',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
